jarkko-authentication:
  #build: .
  image: jaquinonesg/jarkko_authentication
  ports:
    - "4000:4000"
authentication-db:
  #build: ./db-server
  image: jaquinonesg/authentication_db
  ports:
    - "3306:3306"